% Clear all so there is no interference from older executions
clear all, clf, close all, clc, format compact




disp('================')
disp('Testcase fig 7.5')
disp('================')
P = create_automaton(...
        {'p1','p2','p3','p4','5','6'},...   % States
        '1',...         			% Initial state
        {'a','b','c','!d'},...   	% Events (Alphabet)
        {'1','a','2';...
        '2','b','4';...
        '5','b','4';...
        '1','c','3';...
        '2','!d','5';...
        '5','!d','6';...
        '3','!d','4'},...			% Transitions (source, event, target)
        {'4'});						% Marked states			
Sp = create_automaton(...
        {'1','2','3','4','5'},...   	% States
        '1',...         			% Initial state
        {'a', 'b','c','!d'},...   	% Events (Alphabet)
        {'1','a','2';...
         '2','b','4';...
         '5','b','4';...
         '1','c','3';...
         '2','!d','5';...
         '3','!d','4'},... % Transitions (source, event, target)
        {'4'});   % Marked states

S_7_5 = supervisor(P,Sp,{'!d'})

% =======================================
% ======        TESTCASE 3          =====
% ====== figure 7.6 lecture notes   =====
% =======================================
disp('================')
disp('Testcase fig 7.6')
disp('================')
P1 = create_automaton(...
        {'p11','p12'},...   % States
        'p11',...                     % Initial state
        {'a','b'},...      % Events (Alphabet)
        {'p11','a','p12';...
        'p12','b','p11'});% ...           % Transitions (source, event, target)
        % {'p4'});
P2 = create_automaton(...
        {'p21','p22'},...   % States
        'p21',...                     % Initial state
        {'c','d','e'},...      % Events (Alphabet)
        {'p21','c','p22';...
        'p22','d','p21';...
        'p22','e','p21'});% ...           % Transitions (source, event, target)
        % {'p4'});                     % Marked states         
Sp1 = create_automaton(...
        {'Sp11','Sp12'},...   % States
        'Sp11',...                     % Initial state
        {'b','c'},...      % Events (Alphabet)
        {'Sp11','b','Sp12';...
        'Sp12','c','Sp11'},...           % Transitions (source, event, target)
        {'Sp11'});                     % Marked states  
Sp2 = create_automaton(...
        {'Sp21','Sp22'},...   % States
        'Sp21',...                     % Initial state
        {'c','d'},...      % Events (Alphabet)
        {'Sp21','c','Sp22';...
        'Sp22','d','Sp21'},...           % Transitions (source, event, target)
        {'Sp21'});                       

P1P2  = synch(P1,P2);
Sp1Sp2  = synch(Sp1,Sp2);

S_7_6 = supervisor(P1P2,Sp1Sp2,{'b'})


disp('=================')
disp('== Exam task 3 ==')
disp('=================')
P = create_automaton(...
        {'p1','p2','p3','p4','p5','p6','p7','p8','p9'},...   % States
        'p1',...                     % Initial state
        {'a','b','c','d','e'},...      % Events (Alphabet)
        {'p1','a','p2';...
        'p7','a','p6';...
        'p1','b','p4';...
        'p5','b','p6';...
        'p1','c','p3';...
        'p2','c','p5';...
        'p4','c','p7';...
        'p9','c','p8';...
        'p3','d','p6';...
        'p5','d','p6';...
        'p8','d','p6';...
        'p7','e','p9'});%...           % Transitions (source, event, target)
        % {'p4'});                     % Marked states
Sp = create_automaton(...
        {'Sp1','Sp2','Sp3','Sp4'},...       % States
        'Sp1',...                     % Initial state
        {'a', 'b','d'},...     % Events (Alphabet)
        {'Sp1','a','Sp2';...
         'Sp3','a','Sp4';...
         'Sp1','b','Sp3';...
         'Sp2','b','Sp4';...
         'Sp1','d','Sp4'},... % Transitions (source, event, target)
        {'Sp4'});   % Marked states

S_exam_task_3 = supervisor(P,Sp, {'d','e'})





